sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - 10
cache:
  yarn: true
before_install:
  #  - npm install -g node-gyp
  - yarn global add node-gyp
script:
  - yarn test-ci
  - yarn build-ci
