#sudo: required
language: node_js
node_js:
  - 10
addons:
  chrome: stable
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
cache:
  yarn: true
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

install:
  - CC=gcc-4.9 CXX=g++-4.9 yarn
script:
  - npm install codecov -g
  - yarn test-lib-ci
  - yarn build-lib-ci
after_success:
  - codecov
