#sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - 10
cache:
  yarn: true
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn=1.9.4-1
  - sudo yarn global add node-gyp
script:
  - yarn test-lib-ci
  - yarn build-lib-ci
